'use client'
import {FormEvent,useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createTask,createWorkspace,listWorkspaces,startTask} from '@/lib/api'
import {getDesktopRuntime} from '@/lib/desktop'
import {desktopBridge} from '@/lib/desktop-bridge'
import type {Workspace} from '@/lib/types'

export default function NewTask(){
 const router=useRouter();const [requirement,setRequirement]=useState('');const [acceptance,setAcceptance]=useState('');const [workspaces,setWorkspaces]=useState<Workspace[]>([]);const [workspaceID,setWorkspaceID]=useState('');const [loadingWorkspaces,setLoadingWorkspaces]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;async function load(){try{let available=await listWorkspaces();const bridge=desktopBridge();if(bridge){try{const status=await bridge.status();if(status.state==='ready'&&status.workspace&&!available.some(workspace=>workspace.root===status.workspace)){const registered=await createWorkspace(status.workspace);available=[registered,...available]}}catch{/* The API list remains usable when the local runtime is stopped. */}}if(active){setWorkspaces(available);setWorkspaceID(current=>current||available[0]?.id||'')}}catch(err){if(active)setError(err instanceof Error?err.message:'无法加载工作区')}finally{if(active)setLoadingWorkspaces(false)}}void load();return()=>{active=false}},[])
 async function submit(e:FormEvent){e.preventDefault();if(!workspaceID||!requirement.trim()||!acceptance.trim())return;setBusy(true);setError('');try{const task=await createTask({workspaceId:workspaceID,requirement,acceptance:acceptance.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)});await startTask(task.id);router.push(getDesktopRuntime()?`/tasks/view?id=${encodeURIComponent(task.id)}`:`/tasks/${task.id}`)}catch(err){setError(err instanceof Error?err.message:'任务提交失败');setBusy(false)}}
 return <><h1>新建任务</h1><form className="card" onSubmit={submit}><label>工作区<select required value={workspaceID} onChange={event=>setWorkspaceID(event.target.value)} disabled={loadingWorkspaces}><option value="">{loadingWorkspaces?'正在加载工作区…':'请选择已注册工作区'}</option>{workspaces.map(workspace=><option key={workspace.id} value={workspace.id}>{workspace.root}{workspace.dirty?'（Git 有未提交更改）':''}</option>)}</select></label>{!loadingWorkspaces&&!workspaces.length&&<p role="alert">尚未注册工作区。桌面版请先选择工作区并启动本地服务。</p>}<label>需求<textarea required value={requirement} onChange={e=>setRequirement(e.target.value)} /></label><label>验收标准<textarea required value={acceptance} onChange={e=>setAcceptance(e.target.value)} placeholder="每行一条" /></label><label>Quorum<input type="number" min="1" max="9" defaultValue="2" /></label><label>最大轮次<input type="number" min="1" max="5" defaultValue="2" /></label>{error&&<p role="alert">{error}</p>}<button type="submit" disabled={busy||loadingWorkspaces||!workspaceID}>{busy?'正在启动…':'开始协作分析'}</button></form></>}
