export type Command = { executable:string; args:string[]; work_dir?:string; timeout_seconds?:number; purpose?:string }
export type Patch = { path:string; unified_diff:string; before_hash?:string }
export type ExecutionPlan = { version:number; patches:Patch[]; commands:Command[]; acceptance:string[]; recovery:string[] }
export type Task = { id:string; state:string; workspace_id?:string; requirement:string; acceptance?:string[]; plan_version?:number; approval_hash?:string; approved?:boolean; plan?:ExecutionPlan }
export type Workspace = { id:string; root:string; is_git:boolean; dirty:boolean }
export type APIError = { code:string; message:string; fields?:Record<string,string> }
export type Envelope<T> = { data:T; error?:APIError; request_id:string }
export type Identity = { subject:string; roles:string[]; permissions:string[]; expires_at:string|null }
export type ManagedUser = { subject:string; disabled:boolean; roles:string[] }
export type ManagedRole = { name:string; permissions:string[] }
export type Permission = { name:string }
export type CreateUserInput = { subject:string; password:string; roles:string[] }
export type UpdateUserInput = { password?:string; roles?:string[]; disabled?:boolean }
export type CreateRoleInput = { name:string; permissions:string[] }
export type UpdateRoleInput = { permissions:string[] }
